services:
  - type: web
    name: tubenova-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app --preload --workers=2 --threads=2 --timeout=120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: YDL_ALLOWED_ORIGINS
        value: "*"